name=input("이름을 입력하세요:")
print("안녕하세요.",name + "님!")
print("엄마와 함께 AI 에이전트입니다.")
print("오늘도 함께 한 걸음 나아가 볼까요?")
mood = input("오늘 기분은 어떠신가요?")
print("오늘 기분은", mood)
print("말해 주셔서 감사합니다.")
print("오늘도 함께 한 걸음 나아가 봅시다!")
